keyboard:
  matrix_positions:
    - [[1,1], [2,1], [3,1], [4,1], [5,1], [6,1],                  [13,1], [14,1], [15,1], [16,1], [17,1], [18,1]]
    - [[1,2], [2,2], [3,2], [4,2], [5,2], [6,2],                  [13,2], [14,2], [15,2], [16,2], [17,2], [18,2]]
    - [[1,3], [2,3], [3,3], [4,3], [5,3], [6,3],                  [13,3], [14,3], [15,3], [16,3], [17,3], [18,3]]
    - [                            [5,4], [6,4], [7,4],   [12,4], [13,4], [14,4]                                ]

  positions:
    - [[0.5, 65.5], [50.5, 65.5], [100.5, 55.5], [150.5, 50.5], [200.5, 55.5], [250.5, 60.6],                              [450.5, 60.5], [500.5, 55.5], [550.5, 50.5], [600.5, 55.5], [650.5, 65.5], [700.6, 65.5]]
    - [[0.5,115.5], [50.5,115.5], [100.5,105.5], [150.5,100.5], [200.5,105.5], [250.5,110.5],                              [450.5,110.5], [500.5,105.5], [550.5,100.5], [600.5,105.5], [650.5,115.5], [700.6,115.5]]
    - [[0.5,165.5], [50.5,165.5], [100.5,155.5], [150.5,150.5], [200.5,155.5], [250.5,160.5],                              [450.5,160.5], [500.5,155.5], [550.5,150.5], [600.5,155.5], [650.5,165.5], [700.6,165.5]]
    - [                                                   [175.5,210.5],    [230.5,210.5],  [290.5,210.5],   [410.5,210.5],   [470.5,210.5],    [525.5,210.5]                                                      ]

  hands:
    - [Left, Left, Left, Left, Left, Left,                Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left, Left,                Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left, Left,                Right, Right, Right, Right, Right, Right]
    - [                        Left, Left, Left,   Right, Right, Right                            ]

  fingers:
    - [Pinky, Pinky, Ring,  Middle, Index, Index,                 Index, Index, Middle, Ring,  Pinky, Pinky]
    - [Pinky, Pinky, Ring,  Middle, Index, Index,                 Index, Index, Middle, Ring,  Pinky, Pinky]
    - [Pinky, Pinky, Ring,  Middle, Index, Index,                 Index, Index, Middle, Ring,  Pinky, Pinky]
    - [                             Thumb,   Thumb,   Thumb,   Thumb, Thumb,   Thumb,                              ]

  key_costs:
    - [25, 20,  9,  5, 11, 17,           17, 11,  5,  9, 20, 25]
    - [ 9,  5,  3,  2,  2,  8,            8,  2,  2,  3,  5,  9]
    - [25, 10, 11, 11,  7, 11,           11,  7, 11, 11, 10, 25]
    - [                 6,  3,  6,    6,  3,  6                ]

  unbalancing_positions:
    - [[-1,  1], [0, 0.5], [0,   0], [0,  0], [0, 0.5], [1,    1],                  [-1,    1], [0, 0.5], [0, 0], [0,   0], [0, 0.5], [1,  1]]
    - [[-1,  0], [0,   0], [0,   0], [0,  0], [0,   0], [1,    0],                  [-1,    0], [0,   0], [0, 0], [0,   0], [0,   0], [1,  0]]
    - [[-1, -1], [0,   0], [0,   0], [0,  0], [0,   0], [1,   -1],                  [-1,   -1], [0,   0], [0, 0], [0,   0], [0,   0], [1, -1]]
    - [                                       [0,   0], [0,    0],  [0, 0], [0, 0], [0,   0],   [0,   0],                                    ]

  symmetries:
    - [  9, 10, 11, 12, 13, 14,           14, 13, 12, 11, 10,  9]
    - [ 15, 16, 17, 18, 19, 20,           20, 19, 18, 17, 16, 15]
    - [ 21, 22, 23, 24, 25, 26,           26, 25, 24, 23, 22, 21]
    - [                 27, 28, 29,   29, 28, 27                ]

  home_row_positions:
    Left:
      Pinky: [50.5, 115.5]
      Ring: [100.5, 115.5]
      Middle: [150.5, 115.5]
      Index: [200.5, 115.5]
      Thumb: [230.5, 210.5]
    Right:
      Pinky: [650.5, 115.5]
      Ring: [600.5, 115.5]
      Middle: [550.5, 115.5]
      Index: [500.5, 115.5]
      Thumb: [470.5, 210.5]


  plot_template: |2
                ┌───┐                         ┌───┐
            ┌───┤ {{3}} ├───┬───┐         ┌───┬───┤ {{8}} ├───┐
    ┌───┬───┤ {{2}} ├───┤ {{4}} │ {{5}} │         │ {{6}} │ {{7}} ├───┤ {{9}} ├───┬───┐
    │ {{0}} │ {{1}} ├───┤ {{15}} ├───┼───┤         ├───┼───┤ {{20}} ├───┤ {{10}} │ {{11}} │
    ├───┼───┤ {{14}} ├───┤ {{16}} │ {{17}} │         │ {{18}} │ {{19}} ├───┤ {{21}} ├───┼───┤
    │ {{12}} │ {{13}} ├───┤ {{27}} ├─━─┼───┤         ├───┼─━─┤ {{32}} ├───┤ {{22}} │ {{23}} │
    ├───┼───┤ {{26}} ├───┤ {{28}} │ {{29}} │         │ {{30}} │ {{31}} ├───┤ {{33}} ├───┼───┤
    │ {{24}} │ {{25}} ├───┘   └───┴───┘         └───┴───┘   └───┤ {{34}} │ {{35}} │
    └───┴───┘       ┌───┬───┬───┐ ┌───┬───┬───┐       └───┴───┘
                    │ {{36}} │ {{37}} │ {{38}} │ │ {{39}} │ {{40}} │ {{41}} │
                    └───┴───┴───┘ └───┴───┴───┘


  plot_template_short: |2
    {{0}}{{1}}{{2}}{{3}}{{4}}{{5}} {{6}}{{7}}{{8}}{{9}}{{10}}{{11}}
    ⇘{{12}}{{13}}{{14}}{{15}}{{16}} {{17}}{{18}}{{19}}{{20}}{{21}}⇘
     {{22}}{{23}}{{24}}{{25}}{{26}} {{27}}{{28}}{{29}}{{30}}{{31}}

base_layout:
  keys:
    # Row 1
    - - ["x", "X", "ſ", "−", "ξ", "Ξ"]
      - ["v", "V", "…", "⇞", "", "√"]
      - ["l", "L", "_", "⌫", "λ", "Λ"]
      - ["c", "C", "[", "⇡", "χ", "ℂ"]
      - ["w", "W", "]", "⌦", "ω", "Ω"]
      - ["k", "K", "^", "⇟", "κ", "×"]
      - ["h", "H", "!", "¡", "ψ", "Ψ"]
      - ["g", "G", "<", "7", "γ", "Γ"]
      - ["f", "F", ">", "8", "φ", "Φ"]
      - ["q", "Q", "=", "9", "ϕ", "ℚ"]
      - ["y", "Y", "&", "+", "υ", "∇"]
      - ["ß", "ẞ", "@", "-", "ς", "∘"]
    # Row 2 (home row)
    - - ["⇩"]
      - ["u", "U", "\\", "⇱", "", "⊂"]
      - ["i", "I", "/", "⇠", "ι", "∫"]
      - ["a", "A", "{",  "⇣", "α", "∀"]
      - ["e", "E", "}", "⇢", "ε", "∃"]
      - ["o", "O", "*", "⇲", "ο", "∈"]
      - ["s", "S", "?", "¿", "σ", "Σ"]
      - ["n", "N", "(", "4", "ν", "ℕ"]
      - ["r", "R", ")", "5", "ρ", "ℝ"]
      - ["t", "T", "-", "6", "τ", "∂"]
      - ["d", "D", ":", ",", "δ", "Δ"]
      - ["⇘"]
    # Row 3
    - - [""]
      - ["ü", "Ü", "#", "", "", "∪"]
      - ["ö", "Ö", "$", "\t", "ϵ", "∩"]
      - ["ä", "Ä", "|", "⎀", "η", "ℵ"]
      - ["p", "P", "~", "\n", "π", "Π"]
      - ["z", "Z", "`", "↶", "ζ", "ℤ"]
      - ["b", "B", "+", ":", "β", "⇐"]
      - ["m", "M", "%", "1", "μ", "⇔"]
      - [",", "–", '"', "2", "ϱ", "⇒"]
      - [".", "•", "'", "3", "ϑ", "↦"]
      - ["j", "J", ";", ".", "θ", "Θ"]
      - [""]
    # Row 4, containing the spacebar
    - - ["⇚"]
      - ["⇧"]
      - ["\t"]
      - ["\n"]
      - [" ", " ", " ", "0", " ", " "]
      - ["⇙"]

  fixed_keys:
    - [ false, false, false, false, false, false,                  false, false, false, false, false, false]
    - [  true, false, false, false, false, false,                  false, false, false, false, false,  true]
    - [  true, false, false, false, false, false,                  false, false, false, false, false,  true]
    - [                              true,  true,  true,    true,  true,  true                             ]

  # for NeoLayoutGenerator:
  # layers that shall not be permutated (starting from 0)
  fixed_layers: [2, 3]

  # for GroupedLayoutGenerator:
  # number of consecutive symbols from base layout to group together generating a layout
  grouped_layers: 2

  modifiers:
    - Left:
        type: hold
        value: [[6,4]]
      Right:
        type: hold
        value: [[6,4]]
    - Left:
        type: hold
        value: [[1,2]]
      Right:
        type: hold
        value: [[18,2]]
    - Left:
        type: hold
        value: [[5,4]]
      Right:
        type: hold
        value: [[14,4]]
    - Left:
        type: hold
        value: [[6,4],[5,4]]
      Right:
        type: hold
        value: [[6,4],[14,4]]
    - Left:
        type: hold
        value: [[1,2],[5,4]]
      Right:
        type: hold
        value: [[18,2],[14,4]]
