keyboard:
  matrix_positions:
    - [       [3,0], [4,0], [5,0],                                 [14,0], [15,0], [16,0]        ]
    - [[2,1], [3,1], [4,1], [5,1],                                 [14,1], [15,1], [16,1], [17,1]]
    - [       [3,2], [4,2], [5,2],                                 [14,2], [15,2], [16,2]        ]
    - [[2,3], [3,3], [4,3], [5,3],                                 [14,3], [15,3], [16,3], [17,3]]
    - [                            [6,4], [7,4],   [12,4], [13,4]                                ]

  positions:
    - [              [100.5,5.5], [150.5,0.5], [200.5,5.5],                              [500.5,5.5], [550.5,0.5], [600.5,5.5]               ]
    - [[50.5,65.5], [100.5,55.5], [150.5,50.5], [200.5,55.5],                              [500.5,55.5], [550.5,50.5], [600.5,55.5], [650.5,65.5]]
    - [              [100.5,105.5], [150.5,100.5], [200.5,105.5],                              [500.5,105.5], [550.5,100.5], [600.5,105.5]               ]
    - [[50.5,165.5], [100.5,155.5], [150.5,150.5], [200.5,155.5],                              [500.5,155.5], [550.5,150.5], [600.5,155.5], [650.5,165.5]]
    - [                                                        [230.5,210.5],  [290.5,210.5],   [410.5,210.5],   [470.5,210.5]                           ]

  hands:
    - [      Left, Left, Left,                              Right, Right, Right       ]
    - [Left, Left, Left, Left,                              Right, Right, Right, Right]
    - [      Left, Left, Left,                              Right, Right, Right       ]
    - [Left, Left, Left, Left,                              Right, Right, Right, Right]
    - [                        Left, Left,    Right, Right                            ]

  fingers:
    - [       Ring,  Middle, Index,                                 Index, Middle, Ring        ]
    - [Pinky, Ring,  Middle, Index,                                 Index, Middle, Ring,  Pinky]
    - [       Ring,  Middle, Index,                                 Index, Middle, Ring        ]
    - [Pinky, Ring,  Middle, Index,                                 Index, Middle, Ring,  Pinky]
    - [                             Thumb,   Thumb,   Thumb, Thumb                    ]

  key_costs:
    - [    18, 15, 21,                    21, 15, 18    ]
    - [17, 13, 12, 12,                    12, 12, 13, 17]
    - [     8,  5, 11,                    11,  5,  8    ]
    - [ 7,  3,  2,  2,                     2,  2,  3,  7]
    - [                  3,  6,    6,  3                ]

  unbalancing_positions:
    - [          [0,   0], [0,  0], [0,   0],                  [0,   0], [0, 0], [0,   0]          ]
    - [[0,   0], [0,   0], [0,  0], [0,   0],                  [0,   0], [0, 0], [0,   0], [0,   0]]
    - [          [0,   0], [0,  0], [0,   0],                  [0,   0], [0, 0], [0,   0]          ]
    - [[0,   0], [0,   0], [0,  0], [0,   0],                  [0,   0], [0, 0], [0,   0], [0,   0]]
    - [                                 [0, 0],   [0, 0], [0, 0], [0,   0]                                       ]

  symmetries:
    - [    17, 18, 19,           19, 18, 17    ]
    - [22, 23, 24, 25,           25, 24, 23, 22]
    - [    17, 18, 19,           19, 18, 17    ]
    - [22, 23, 24, 25,           25, 24, 23, 22]
    - [                28, 29,   29, 28                ]

  home_row_positions:
    Left:
      Pinky: [50.5,165.5]
      Ring: [100.5,155.5]
      Middle: [150.5,150.5]
      Index: [200.5,155.5]
      Thumb: [230.5, 210.5]
    Right:
      Pinky: [650.5,165.5]
      Ring: [600.5,155.5] 
      Middle: [550.5,150.5] 
      Index: [500.5,155.5] 
      Thumb: [470.5, 210.5]


  plot_template: |2
            ┌───┐                         ┌───┐
        ┌───┤ {{1}} ├───┐                 ┌───┤ {{4}} ├───┐
        │ {{0}} ├───┤ {{2}} │                 │ {{3}} ├───┤ {{5}} │
        ├───┤ {{8}} ├───┤                 ├─━─┤ {{11}} ├───┤ 
    ┌───┤ {{7}} ├───┤ {{9}} │                 │ {{10}} ├───┤ {{12}} ├───┐
    │ {{6}} ├───┘   └───┘                 └───┘   └───┤ {{13}} │
    └───┘                                         └───┘
            ┌───┐                         ┌───┐
        ┌───┤ {{15}} ├───┐                 ┌───┤ {{18}} ├───┐
        │ {{14}} ├───┤ {{16}} │                 │ {{17}} ├───┤ {{19}} │
        ├───┤ {{22}} ├───┤                 ├─━─┤ {{25}} ├───┤ 
    ┌───┤ {{21}} ├───┤ {{23}} │                 │ {{24}} ├───┤ {{26}} ├───┐
    │ {{20}} ├───┘   └───┘                 └───┘   └───┤ {{27}} │
    └───┘           ┌───┬───┐ ┌───┬───┐           └───┘
                    │ {{28}} │ {{29}} │ │ {{30}} │ {{31}} │
                    └───┴───┘ └───┴───┘

  plot_template_short: |2
    {{0}}{{1}}{{2}} {{3}}{{4}}{{5}}
    {{6}}{{7}}{{8}}{{9}} {{10}}{{11}}{{12}}{{13}}
    {{14}}{{15}}{{16}} {{17}}{{18}}{{19}}
    {{20}}{{21}}{{22}}{{23}} {{24}}{{25}}{{26}}{{27}}

    {{28}}{{29}} {{30}}{{31}}

base_layout:
  keys:
    # Row 0 (actually layer 1)
    - - ["v"]
      - ["m"]
      - ["w"]
      - ["f"]
      - [","]
      - ["z"]
    # Row 1 (actually layer 1)
    - - ["q"]
      - ["j"]
      - ["k"]
      - ["p"]
      - ["b"]
      - ["."]
      - ["x"]
      - ["y"]
    # Row 2
    - - ["l"]
      - ["d"]
      - ["g"]
      - ["h"]
      - ["u"]
      - ["o"]
    # Row 3 (home row)
    - - ["i"]
      - ["s"]
      - ["t"]
      - ["r"]
      - ["n"]
      - ["e"]
      - ["a"]
      - ["c"]
    # Row 4, containing the spacebar
    - - [" "]
      - ["⇧"]
      - ["R"]
      - ["⇙"]

  fixed_keys:
    - [         false, false, false,                  false, false, false       ]
    - [  false, false, false, false,                  false, false, false, false]
    - [         false, false, false,                  false, false, false       ]
    - [  false, false, false, false,                  false, false, false, false]
    - [                        true,  true,    true,  true                      ]

  # starting from 0
  fixed_layers: [1]

  modifiers:
    - Left:
        type: hold
        value: [[12,4]]
      Right:
        type: hold
        value: [[12,4]]
