keyboard:
  matrix_positions:
    - [[1,1], [2,1], [3,1], [4,1],                                 [ 9,1], [10,1], [11,1], [12,1]]
    - [[1,2], [2,2], [3,2], [4,2],                                 [ 9,2], [10,2], [11,2], [12,2]]
    - [[1,3], [2,3], [3,3], [4,3],                                 [ 9,3], [10,3], [11,3], [12,3]]
    - [[1,4], [2,4], [3,4], [4,4],                                 [ 9,4], [10,4], [11,4], [12,4]]
    - [                              [5,5], [6,5], [7,5], [8,5]                                  ]

  positions:
    - [[ 50.0,  50.0], [100.0,  50.0], [150.0,  50.0], [200.0,  50.0],        [450.0,  50.0], [500.0,  50.0], [550.0,  50.0], [600.0,  50.0]]
    - [[ 50.0, 100.0], [100.0, 100.0], [150.0, 100.0], [200.0, 100.0],        [450.0, 100.0], [500.0, 100.0], [550.0, 100.0], [600.0, 100.0]]
    - [[ 50.0, 150.0], [100.0, 150.0], [150.0, 150.0], [200.0, 150.0],        [450.0, 150.0], [500.0, 150.0], [550.0, 150.0], [600.0, 150.0]]
    - [[ 50.0, 200.0], [100.0, 200.0], [150.0, 200.0], [200.0, 200.0],        [450.0, 200.0], [500.0, 200.0], [550.0, 200.0], [600.0, 200.0]]
    - [                                     [250.0, 250.0], [300.0, 250.0], [350.0, 250.0], [400.0, 250.0]]

  hands:
    - [Left, Left, Left, Left,                                     Right, Right, Right, Right ]
    - [Left, Left, Left, Left,                                     Right, Right, Right, Right ]
    - [Left, Left, Left, Left,                                     Right, Right, Right, Right ]
    - [Left, Left, Left, Left,                                     Right, Right, Right, Right ]
    - [                               Left, Left, Right, Right                                ]

  fingers:
    - [Pinky, Ring,  Middle, Index,                                Index, Middle, Ring,  Pinky]
    - [Pinky, Ring,  Middle, Index,                                Index, Middle, Ring,  Pinky]
    - [Pinky, Ring,  Middle, Index,                                Index, Middle, Ring,  Pinky]
    - [Pinky, Ring,  Middle, Index,                                Index, Middle, Ring,  Pinky]
    - [                              Thumb,   Thumb, Thumb, Thumb                             ]

  key_costs:
    - [ 5,  3,  2,  2,                     2,  2,  3,  5]
    - [ 6,  4,  3,  3,                     3,  3,  4,  6]
    - [ 5,  3,  2,  2,                     2,  2,  3,  5]
    - [ 5,  3,  2,  2,                     2,  2,  3,  5]
    - [                  6,  4,    4,  6                ]

  unbalancing_positions:
    - [[0,0], [0,0], [0,0], [0,0],                                 [ 0,0], [0,0], [0,0], [0,0]]
    - [[0,0], [0,0], [0,0], [0,0],                                 [ 0,0], [0,0], [0,0], [0,0]]
    - [[0,0], [0,0], [0,0], [0,0],                                 [ 0,0], [0,0], [0,0], [0,0]]
    - [[0,0], [0,0], [0,0], [0,0],                                 [ 0,0], [0,0], [0,0], [0,0]]
    - [                              [0,0], [0,0], [0,0], [0,0]                                  ]

  symmetries:
    - [ 1,  2,  3,  4,                     4,  3,  2,  1]
    - [11, 12, 13, 14,                    14, 13, 12, 11]
    - [21, 22, 23, 24,                    24, 23, 22, 21]
    - [31, 32, 33, 34,                    34, 33, 32, 31]
    - [                 45, 46,   46,  45               ]


  home_row_positions:
    Left:
      Pinky:  [ 50.0, 200.0]
      Ring:   [100.0, 200.0]
      Middle: [150.0, 200.0]
      Index:  [200.0, 200.0]
      Thumb:  [300.0, 250.0]
    Right:
      Pinky:  [600.0, 200.0]
      Ring:   [550.0, 200.0]
      Middle: [500.0, 200.0]
      Index:  [450.0, 200.0]
      Thumb:  [350.0, 250.0]


  plot_template: |2
 ┌───┬───┬───┬───┐                 ┌───┬───┬───┬───┐ 
 │ {{0}} │ {{1}} │ {{2}} │ {{3}} │                 │ {{4}} │ {{5}} │ {{6}} │ {{7}} │
 ├───┼───┼───┼───┤                 ├───┼───┼───┼───┤
 │ {{8}} │ {{9}} │ {{10}} │ {{11}} │                 │ {{12}} │ {{13}} │ {{14}} │ {{15}} │
 ├───┼───┼───┼───┤                 ├───┼───┼───┼───┤
 │ {{16}} │ {{17}} │ {{18}} │ {{19}} │                 │ {{20}} │ {{21}} │ {{22}} │ {{23}} │
 ├───┼───┼───┼───┤                 ├───┼───┼───┼───┤
 │ {{24}} │ {{25}} │ {{26}} │ {{27}} │                 │ {{28}} │ {{29}} │ {{30}} │ {{31}} │
 └───┴───┴───┴───┘                 └───┴───┴───┴───┘
                 ┌───┬───┐ ┌───┬───┐                 
                 │ {{32}} │ {{33}} │ │ {{34}} │ {{35}} │
                 └───┴───┘ └───┴───┘

  plot_template_short: |2
{{0}}{{1}}{{2}}{{3}}     {{4}}{{5}}{{6}}{{7}}
{{8}}{{9}}{{10}}{{11}}   {{12}}{{13}}{{14}}{{15}}
{{16}}{{17}}{{18}}{{19}} {{20}}{{21}}{{22}}{{23}}
{{24}}{{25}}{{26}}{{27}} {{28}}{{29}}{{30}}{{31}}
            {{32}}{{33}}{{34}}{{35}}

base_layout:
  keys:
    # Row 1
    - - ["a"]
      - ["b"]
      - ["c"]
      - ["d"]
      - ["e"]
      - ["f"]
      - ["g"]
      - ["ü"]
    # Row 2
    - - ["h"]
      - ["i"]
      - ["j"]
      - ["k"]
      - ["l"]
      - ["m"]
      - ["n"]
      - ["⇧"]
    # Row 3
    - - ["o"]
      - ["p"]
      - ["q"]
      - ["r"]
      - ["s"]
      - ["t"]
      - ["u"]
      - ["⇧"]
    # Row 4
    - - ["v"]
      - ["w"]
      - ["x"]
      - ["y"]
      - ["z"]
      - ["ä"]
      - ["ö"]
      - ["⇧"]
    # Row 5
    - - ["⇘"]
      - ["⇧"]
      - [" "]
      - ["⇙"]

  fixed_keys:
    - [false, false, false, false,                                false, false, false, false ]
    - [false, false, false, false,                                false, false, false, true  ]
    - [false, false, false, false,                                false, false, false, true  ]
    - [false, false, false, false,                                false, false, false, true  ]
    - [                             true,  true,    false,  true                             ]

  # for NeoLayoutGenerator:
  # layers that shall not be permutated (starting from 0)
  fixed_layers: [1]

  # for GroupedLayoutGenerator:
  # number of consecutive symbols from base layout to group together generating a layout
  grouped_layers: 0

