keyboard:
  matrix_positions:
    - [[1,0], [2,0], [3,0], [4,0], [5,0], [6,0],                [13,0], [14,0], [15,0], [16,0], [17,0], [18,0]]
    - [[1,1], [2,1], [3,1], [4,1], [5,1], [6,1],                [13,1], [14,1], [15,1], [16,1], [17,1], [18,1]]
    - [[1,2], [2,2], [3,2], [4,2], [5,2], [6,2],                [13,2], [14,2], [15,2], [16,2], [17,2], [18,2]]
    - [[1,3], [2,3], [3,3], [4,3], [5,3], [6,3], [9,3], [12,3], [13,3], [14,3], [15,3], [16,3], [17,3], [18,3]]
    - [                   [4,4], [5,4], [6,4],  [9,4],    [12,4],  [13,4], [14,4], [15,4]                     ]

  positions:
    - [[0.5,  2.5], [50.5,  2.0], [100.5,  1.0], [150.5,  0.5], [200.5,  1.0], [250.5,  1.7],                                 [450.5,  1.7], [500.5,  1.0], [550.5,  0.5], [600.5,  1.0], [650.5,  2.0], [700.5,  2.5]]
    - [[0.5, 52.5], [50.5, 52.0], [100.5, 51.0], [150.5, 50.5], [200.5, 51.0], [250.5, 51.7],                                 [450.5, 51.7], [500.5, 51.0], [550.5, 50.5], [600.5, 51.0], [650.5, 52.0], [700.5, 52.5]]
    - [[0.5,102.5], [50.5,102.0], [100.5,101.0], [150.5,100.5], [200.5,101.0], [250.5,101.7],                                 [450.5,101.7], [500.5,101.0], [550.5,100.5], [600.5,101.0], [650.5,102.0], [700.5,102.5]]
    - [[0.5,152.5], [50.5,152.0], [100.5,151.0], [150.5,150.5], [200.5,151.0], [250.5,151.7], [300.5,126.0],   [400.5,126.0], [450.5,151.7], [500.5,151.0], [550.5,150.5], [600.5,151.0], [650.5,152.0], [700.5,152.5]]
    - [                                   [125.5,201.5], [175.5,201.5], [225.5,201.5],       [300.5,201.5],     [400.5,201.5],      [475.5,201.5], [525.5,201.5], [575.5,201.5]                                       ]

  hands:
    - [Left, Left, Left, Left, Left, Left,               Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left, Left,               Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left, Left,               Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left, Left, Left,  Right, Right, Right, Right, Right, Right, Right]
    - [                Left, Left, Left,  Left,    Right,  Right, Right, Right                   ]

  fingers:
    - [Pinky, Pinky, Ring, Middle, Index, Index,               Index, Index, Middle, Ring, Pinky, Pinky]
    - [Pinky, Pinky, Ring, Middle, Index, Index,               Index, Index, Middle, Ring, Pinky, Pinky]
    - [Pinky, Pinky, Ring, Middle, Index, Index,               Index, Index, Middle, Ring, Pinky, Pinky]
    - [Pinky, Pinky, Ring, Middle, Index, Index, Index, Index, Index, Index, Middle, Ring, Pinky, Pinky]
    - [                    Thumb,  Thumb, Thumb, Thumb, Thumb, Thumb, Thumb,  Thumb                    ]

  key_costs:
    - [70, 60, 50, 50, 50, 60,         60, 50, 50, 50, 60, 70]
    - [20, 17, 15,  5, 12, 17,         17, 12,  5, 15, 17, 20]
    - [ 9,  5,  3,  3,  3,  6,          6,  3,  3,  3,  5,  9]
    - [20, 11, 22, 22, 10, 15, 18, 18, 15, 10, 22, 22, 11, 20]
    - [          20,  5,  3,   3,    3,   3,  5, 20          ]

  unbalancing_positions:
    - [[-1,  2], [0,   1], [0,   1], [0,  1], [0,   1], [1,    2],                         [-1,    2], [0,   1], [0, 1], [0,   1], [0,   1], [1,  2]]
    - [[-1,  1], [0, 0.5], [0,   0], [0,  0], [0, 0.5], [1,    1],                         [-1,    1], [0, 0.5], [0, 0], [0,   0], [0, 0.5], [1,  1]]
    - [[-1,  0], [0,   0], [0,   0], [0,  0], [0,   0], [1,    0],                         [-1,    0], [0,   0], [0, 0], [0,   0], [0,   0], [1,  0]]
    - [[-1, -1], [0,   0], [0,   0], [0,  0], [0,   0], [1,   -1], [-0.5, 1],   [0.5,  1], [-1,   -1], [0,   0], [0, 0], [0,   0], [0,   0], [1, -1]]
    - [                        [-1, -1], [0,   0], [0,    0],    [0,  0],           [0,  0],    [0,   0],   [0,   0], [1, -1]                       ]

  symmetries:
    - [  1,  2,  3,  4,  5,  6,          6,  5,  4,  3,  2,  1]
    - [  9, 10, 11, 12, 13, 14,         14, 13, 12, 11, 10,  9]
    - [ 15, 16, 17, 18, 19, 20,         20, 19, 18, 17, 16, 15]
    - [ 21, 22, 23, 24, 25, 26, 27, 27, 26, 25, 24, 23, 22, 21]
    - [           28, 29, 30,  31,   31,  30, 29, 28          ]

  finger_resting_positions:
    Left:
      Pinky: [50.5, 102.0]
      Ring: [100.5, 101.0]
      Middle: [150.5, 100.5]
      Index: [200.5, 101.0]
      Thumb: [300.5, 201.5]
    Right:
      Pinky: [600.5, 102.0]
      Ring: [550.5, 101.0]
      Middle: [500.5, 100.5]
      Index: [450.5, 101.0]
      Thumb: [400.5, 201.5]


  plot_template: |2
                ┌───┐                              ┌───┐
            ┌───┤ {{3}} ├───┬───┐              ┌───┬───┤ {{8}} ├───┐
    ┌───┬───┤ {{2}} ├───┤ {{4}} │ {{5}} │              │ {{6}} │ {{7}} ├───┤ {{9}} ├───┬───┐
    │ {{0}} │ {{1}} ├───┤ {{15}} ├───┼───┤              ├───┼───┤ {{20}} ├───┤ {{10}} │ {{11}} │
    ├───┼───┤ {{14}} ├───┤ {{16}} │ {{17}} │              │ {{18}} │ {{19}} ├───┤ {{21}} ├───┼───┤
    │ {{12}} │ {{13}} ├───┤ {{27}} ├───┼───┤              ├───┼───┤ {{32}} ├───┤ {{22}} │ {{23}} │
    ├───┼───┤ {{26}} ├───┤ {{28}} │ {{29}} ├───┐      ┌───┤ {{30}} │ {{31}} ├───┤ {{33}} ├───┼───┤
    │ {{24}} │ {{25}} ├───┤ {{39}} ├─━─┼───┤ {{42}} │      │ {{43}} ├───┼─━─┤ {{46}} ├───┤ {{34}} │ {{35}} │
    ├───┼───┤ {{38}} ├───┤ {{40}} │ {{41}} ├───┘      └───┤ {{44}} │ {{45}} ├───┤ {{47}} ├───┼───┤
    │ {{36}} │ {{37}} ├───┘   └───┴───┘              └───┴───┘   └───┤ {{48}} │ {{49}} │
    └───┴───┘ ┌───┬───┬───┐ ┌───┐      ┌───┐ ┌───┬───┬───┐ └───┴───┘
              │ {{50}} │ {{51}} │ {{52}} │ │ {{53}} │      │ {{54}} │ │ {{55}} │ {{56}} │ {{57}} │
              └───┴───┴───┘ └───┘      └───┘ └───┴───┴───┘


  plot_template_short: |2
    {{0}}{{1}}{{2}}{{3}}{{4}}{{5}}     {{6}}{{7}}{{8}}{{9}}{{10}}{{11}}
    ⇘{{12}}{{13}}{{14}}{{15}}{{16}}     {{17}}{{18}}{{19}}{{20}}{{21}}
    ⇘{{22}}{{23}}{{24}}{{25}}{{26}}     {{27}}{{28}}{{29}}{{30}}{{31}}⇘

base_layout:
  keys:
    # Row 0 (number row)
    - - ["1", "°", "¹", "ª", "₁", "¬"]
      - ["2", "§", "²", "º", "₂", "∨"]
      - ["3", "ℓ", "³", "№", "₃", "∧"]
      - ["4", "»", "›", "", "♀", "⊥"]
      - ["5", "«", "‹", "·", "♂", "∡"]
      - ["6", "$", "¢", "£", "⚥", "∥"]
      - ["7", "€", "¥", "¤", "ϰ", "→"]
      - ["8", "„", "‚", "⇥", "⟨", "∞"]
      - ["9", "“", "‘", "/", "⟩", "∝"]
      - ["0", "”", "’", "*", "₀", "∅"]
      - ["^", "ˇ", "↻", "˙", "˞", "̣"]
      - ["-", "—", "-", "‑", "­", ""]
    # Row 1
    - - ["x", "X", "ſ", "−", "ξ", "Ξ"]
      - ["v", "V", "…", "⇞", "", "√"]
      - ["l", "L", "_", "⌫", "λ", "Λ"]
      - ["c", "C", "[", "⇡", "χ", "ℂ"]
      - ["w", "W", "]", "⌦", "ω", "Ω"]
      - ["k", "K", "^", "⇟", "κ", "×"]
      - ["h", "H", "!", "¡", "ψ", "Ψ"]
      - ["g", "G", "<", "7", "γ", "Γ"]
      - ["f", "F", ">", "8", "φ", "Φ"]
      - ["q", "Q", "=", "9", "ϕ", "ℚ"]
      - ["y", "Y", "&", "+", "υ", "∇"]
      - ["ß", "ẞ", "@", "-", "ς", "∘"]
    # Row 2 (home row)
    - - ["⇩"]
      - ["u", "U", "\\", "⇱", "", "⊂"]
      - ["i", "I", "/", "⇠", "ι", "∫"]
      - ["a", "A", "{",  "⇣", "α", "∀"]
      - ["e", "E", "}", "⇢", "ε", "∃"]
      - ["o", "O", "*", "⇲", "ο", "∈"]
      - ["s", "S", "?", "¿", "σ", "Σ"]
      - ["n", "N", "(", "4", "ν", "ℕ"]
      - ["r", "R", ")", "5", "ρ", "ℝ"]
      - ["t", "T", "-", "6", "τ", "∂"]
      - ["d", "D", ":", ",", "δ", "Δ"]
      - ["⇘"]
    # Row 3
    - - ["⇧"]
      - ["ü", "Ü", "#", "", "", "∪"]
      - ["ö", "Ö", "$", "\t", "ϵ", "∩"]
      - ["ä", "Ä", "|", "⎀", "η", "ℵ"]
      - ["p", "P", "~", "\n", "π", "Π"]
      - ["z", "Z", "`", "↶", "ζ", "ℤ"]
      - ["\t"]
      - ["←"]
      - ["b", "B", "+", ":", "β", "⇐"]
      - ["m", "M", "%", "1", "μ", "⇔"]
      - [",", "–", '"', "2", "ϱ", "⇒"]
      - [".", "•", "'", "3", "ϑ", "↦"]
      - ["j", "J", ";", ".", "θ", "Θ"]
      - ["⇗"]
    # Row 4, containing the spacebar
    - - ["⇚"]
      - ["♕", " ", " ", " ", " ", " "]
      - ["♔"]
      - [" "]
      - ["\n"]
      - ["♔"]
      - ["", "", " ", "0", " ", " "]
      - ["⇙"]


  fixed_keys:
    - [  true,  true,  true,  true,  true,  true,                true,  true,  true,  true,  true,  true]
    - [ false, false, false, false, false, false,               false, false, false, false, false, false]
    - [  true, false, false, false, false, false,               false, false, false, false, false,  true]
    - [  true, false, false, false, false, false,  true,  true, false, false, false, false, false,  true]
    - [                   true,  true,  true,    true,      true,   true,  true,  true                  ]

  # for NeoLayoutGenerator:
  # layers that shall not be permutated (starting from 0)
  fixed_layers: [2, 3]

  # for GroupedLayoutGenerator:
  # number of consecutive symbols from base layout to group together generating a layout
  grouped_layers: 2

  modifiers:
    - Left:
        type: hold
        value: [[1,3]]
      Right:
        type: hold
        value: [[18,3]]
    - Left:
        type: hold
        value: [[1,2]]
      Right:
        type: hold
        value: [[18,2]]
    - Left:
        type: hold
        value: [[4,4]]
      Right:
        type: hold
        value: [[15,4]]
    - Left:
        type: hold
        value: [[1,3], [4,4]]
      Right:
        type: hold
        value: [[18,3], [15,4]]
    - Left:
        type: hold
        value: [[1,2], [4,4]]
      Right:
        type: hold
        value: [[18,2], [15,4]]

