keyboard:
  matrix_positions:
    - [[1,0], [2,0], [3,0], [4,0], [5,0], [6,0], [7,0],                                 [12,0], [13,0], [14,0], [15,0], [16,0], [17,0], [18,0]]
    - [[1,1], [2,1], [3,1], [4,1], [5,1], [6,1], [7,1],                                 [12,1], [13,1], [14,1], [15,1], [16,1], [17,1], [18,1]]
    - [[1,2], [2,2], [3,2], [4,2], [5,2], [6,2], [7,2],                                 [12,2], [13,2], [14,2], [15,2], [16,2], [17,2], [18,2]]
    - [[1,3], [2,3], [3,3], [4,3], [5,3], [6,3],                                                [13,3], [14,3], [15,3], [16,3], [17,3], [18,3]]
    - [[1,4], [2,4], [3,4], [4,4], [5,4], [6,4], [7,4], [8,4], [9,4],   [10,4], [11,4], [12,4], [13,4], [14,4], [15,4], [16,4], [17,4], [18,4]]

  positions:
    - [[0.5, 15.5], [50.5, 15.5], [100.5,  5.5], [150.5,  0.5], [200.5,  5.5], [250.5, 10.5], [300.5, 10.5],                                                                  [400.5, 10.5], [450.5, 10.5], [500.5,  5.5], [550.5,  0.5], [600.5,  5.5], [650.5, 15.5], [700.6, 15.5]]
    - [[0.5, 65.5], [50.5, 65.5], [100.5, 55.5], [150.5, 50.5], [200.5, 55.5], [250.5, 60.6], [300.5, 60.5],                                                                  [400.5, 60.5], [450.5, 60.5], [500.5, 55.5], [550.5, 50.5], [600.5, 55.5], [650.5, 65.5], [700.6, 65.5]]
    - [[0.5,115.5], [50.5,115.5], [100.5,105.5], [150.5,100.5], [200.5,105.5], [250.5,110.5], [300.5,110.5],                                                                  [400.5,110.5], [450.5,110.5], [500.5,105.5], [550.5,100.5], [600.5,105.5], [650.5,115.5], [700.6,115.5]]
    - [[0.5,165.5], [50.5,165.5], [100.5,155.5], [150.5,150.5], [200.5,155.5], [250.5,160.5],                                                                                                [450.5,160.5], [500.5,155.5], [550.5,150.5], [600.5,155.5], [650.5,165.5], [700.6,165.5]]
    - [[0.5,215.5], [50.5,215.5], [100.5,205.5], [150.5,200.5], [200.5,205.5], [250.5,230.5], [275.5,255.5], [300.5,280.5], [325.5,205.5],      [355.5,205.5], [400.5,280.5], [425.5,255.5], [450.5,230.5], [500.5,205.5], [550.5,200.5], [600.5,205.5], [650.5,215.5], [700.5,215.5]]

  hands:
    - [Left, Left, Left, Left, Left, Left, Left,                            Right, Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left, Left, Left,                            Right, Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left, Left, Left,                            Right, Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left, Left,                                         Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left, Left, Left, Left, Left,  Right, Right, Right, Right, Right, Right, Right, Right, Right]

  fingers:
    - [Pinky, Pinky, Ring,  Middle, Index, Index, Index,                          Index, Index, Index, Middle, Ring,  Pinky, Pinky]
    - [Pinky, Pinky, Ring,  Middle, Index, Index, Index,                          Index, Index, Index, Middle, Ring,  Pinky, Pinky]
    - [Pinky, Pinky, Ring,  Middle, Index, Index, Index,                          Index, Index, Index, Middle, Ring,  Pinky, Pinky]
    - [Pinky, Pinky, Ring,  Middle, Index, Index,                                            Index, Index, Middle, Ring,  Pinky, Pinky]
    - [Pinky, Pinky, Ring,  Thumb,  Thumb,   Thumb,   Thumb, Thumb, Thumb, Thumb, Thumb,  Thumb,   Thumb,   Thumb, Thumb,  Ring,  Pinky, Pinky]

  key_costs:
    - [80, 70, 60, 50, 50, 60, 100,                      100, 60, 50, 50, 60, 70, 80]
    - [20, 17, 15,  5, 10, 15,  90,                       90, 15, 10,  5, 15, 17, 20]
    - [ 9,  5,  3,  3,  3,  6,  80,                       80,  6,  3,  3,  3,  5,  9]
    - [20, 11, 22, 22, 12, 17,                                17, 12, 22, 22, 11, 20]
    - [30, 25, 20,  4,  3,       3, 8, 60, 70, 70, 60,  8, 3,      3,  4, 20, 25, 30]

  unbalancing_positions:
    - [[-1,  2], [0,   1], [0,   1], [0,  1], [0,   1], [1,    2], [2, 3],                                                      [-2, 3], [-1,    2], [0,   1], [0,  1], [0,   1], [0,   1], [1,  2]]
    - [[-1,  1], [0, 0.5], [0,   0], [0,  0], [0, 0.5], [1,    1], [2, 2],                                                      [-2, 2], [-1,    1], [0, 0.5], [0,  0], [0,   0], [0, 0.5], [1,  1]]
    - [[-1,  0], [0,   0], [0,   0], [0,  0], [0,   0], [1,    0], [2, 0],                                                      [-2, 0], [-1,    0], [0,   0], [0,  0], [0,   0], [0,   0], [1,  0]]
    - [[-1, -1], [0,   0], [0,   0], [0,  0], [0,   0], [1,   -1],                                                                       [-1,   -1], [0,   0], [0,  0], [0,   0], [0,   0], [1, -1]]
    - [[-1, -2], [-1, -1], [-1 ,-1], [-1,-1], [0,   0],            [0, 0], [1, 0], [2, 0], [3, 1],   [-3, 1], [-2, 0], [-1, 0], [0, 0],              [0,   0], [1, -1], [1  ,-1], [1,  -1], [1, -2]]

  symmetries:
    - [  1,  2,  3,  4,  5,  6,  7,                          7,  6,  5,  4,  3,  2,  1]
    - [  9, 10, 11, 12, 13, 14, 15,                         15, 14, 13, 12, 11, 10,  9]
    - [ 16, 17, 18, 19, 20, 21, 22,                         22, 21, 20, 19, 18, 17, 16]
    - [ 23, 24, 25, 26, 27, 28,                                 28, 27, 26, 25, 24, 23]
    - [ 29, 30, 31, 32, 33,     34, 35, 36, 37, 37, 36, 35, 34,     33, 32, 31, 30, 29]

  finger_resting_positions:
    Left:
      Pinky: [50.5, 115.5]
      Ring: [100.5, 115.5]
      Middle: [150.5, 115.5]
      Index: [200.5, 115.5]
      Thumb: [250.5, 230.5]
    Right:
      Pinky: [650.5, 115.5]
      Ring: [600.5, 115.5]
      Middle: [550.5, 115.5]
      Index: [500.5, 115.5]
      Thumb: [450.5, 230.5]


  plot_template: |2
                ┌───┐                                          ┌───┐
            ┌───┤ {{3}} ├───┬───┐                          ┌───┬───┤ {{10}} ├───┐
    ┌───┬───┤ {{2}} ├───┤ {{4}} │ {{5}} ├───┐                  ┌───┤ {{8}} │ {{9}} ├───┤ {{11}} ├───┬───┐
    │ {{0}} │ {{1}} ├───┤ {{17}} ├───┼───┤ {{6}} │                  │ {{7}} ├───┼───┤ {{24}} ├───┤ {{12}} │ {{13}} │
    ├───┼───┤ {{16}} ├───┤ {{18}} │ {{19}} ├───┤                  ├───┤ {{22}} │ {{23}} ├───┤ {{25}} ├───┼───┤
    │ {{14}} │ {{15}} ├───┤ {{31}} ├───┼───┤ {{20}} │                  │ {{21}} ├───┼───┤ {{38}} ├───┤ {{26}} │ {{27}} │
    ├───┼───┤ {{30}} ├───┤ {{32}} │ {{33}} ├───┤                  ├───┤ {{36}} │ {{37}} ├───┤ {{39}} ├───┼───┤
    │ {{28}} │ {{29}} ├───┤ {{45}} ├─━─┼───┤ {{34}} │                  │ {{35}} ├───┼─━─┤ {{50}} ├───┤ {{40}} │ {{41}} │
    ├───┼───┤ {{44}} ├───┤ {{46}} │ {{47}} ├───┘                  └───┤ {{48}} │ {{49}} ├───┤ {{51}} ├───┼───┤
    │ {{42}} │ {{43}} ├───┤ {{57}} ├───┼───┘┌───────┐        ┌───────┐└───┼───┤ {{68}} ├───┤ {{52}} │ {{53}} │
    ├───┼───┤ {{56}} ├───┤ {{58}} │    │   {{62}}   │        │   {{63}}   │    │ {{67}} ├───┤ {{69}} ├───┼───┤
    │ {{54}} │ {{55}} ├───┘   └───┘    ├───┬───┼───┐┌───┼───┬───┤    └───┘   └───┤ {{70}} │ {{71}} │
    └───┴───┘                │   │   │   ││   │   │   │                └───┴───┘
                             │ {{59}} │ {{60}} │ {{61}} ││ {{64}} │ {{65}} │ {{66}} │
                             └───┴───┴───┘└───┴───┴───┘


  plot_template_short: |2
     {{0}}{{1}}{{2}}{{3}}{{4}} {{5}}{{6}}{{7}}{{8}}{{9}}{{10}}
     {{11}}{{12}}{{13}}{{14}}{{15}} {{16}}{{17}}{{18}}{{19}}{{20}}{{21}}
     {{22}}{{23}}{{24}}{{25}}{{26}} {{27}}{{28}}{{29}}{{30}}{{31}}

base_layout:
  keys:
    # Row 0 (number row)
    - - ["^", "ˇ", "↻", "˙", "˞", "̣"]
      - ["1", "°", "¹", "ª", "₁", "¬"]
      - ["2", "§", "²", "º", "₂", "∨"]
      - ["3", "ℓ", "³", "№", "₃", "∧"]
      - ["4", "»", "›", "", "♀", "⊥"]
      - ["5", "«", "‹", "·", "♂", "∡"]
      - [""]
      - [""]
      - ["6", "$", "¢", "£", "⚥", "∥"]
      - ["7", "€", "¥", "¤", "ϰ", "→"]
      - ["8", "„", "‚", "⇥", "⟨", "∞"]
      - ["9", "“", "‘", "/", "⟩", "∝"]
      - ["0", "”", "’", "*", "₀", "∅"]
      - ["-", "—", "-", "‑", "­", ""]
    # Row 1
    - - ["⇥"]
      - ["x", "X", "…", "⇞", "ξ", "Ξ"]
      - ["v", "V", "_", "⌫", "", "√"]
      - ["l", "L", "[", "⇡", "λ", "Λ"]
      - ["c", "C", "]", "⌦", "χ", "ℂ"]
      - ["w", "W", "^", "⇟", "ω", "Ω"]
      - [""]
      - [""]
      - ["k", "K", "!", "¡", "κ", "×"]
      - ["h", "H", "<", "7", "ψ", "Ψ"]
      - ["g", "G", ">", "8", "γ", "Γ"]
      - ["f", "F", "=", "9", "φ", "Φ"]
      - ["q", "Q", "&", "+", "ϕ", "ℚ"]
      - ["y", "Y", "@", "-", "υ", "∇"]
    # Row 2 (home row)
    - - [""]
      - ["u", "U", "\\", "⇱", "", "⊂"]
      - ["i", "I", "/", "⇠", "ι", "∫"]
      - ["a", "A", "{",  "⇣", "α", "∀"]
      - ["e", "E", "}", "⇢", "ε", "∃"]
      - ["o", "O", "*", "⇲", "ο", "∈"]
      - [""]
      - [""]
      - ["s", "S", "?", "¿", "σ", "Σ"]
      - ["n", "N", "(", "4", "ν", "ℕ"]
      - ["r", "R", ")", "5", "ρ", "ℝ"]
      - ["t", "T", "-", "6", "τ", "∂"]
      - ["d", "D", ":", ",", "δ", "Δ"]
      - ["ß", "ẞ", "ſ", ";", "ς", "∘"]
    # Row 3
    - - [""]
      - ["ü", "Ü", "#", "", "", "∪"]
      - ["ö", "Ö", "$", "\t", "ϵ", "∩"]
      - ["ä", "Ä", "|", "⎀", "η", "ℵ"]
      - ["p", "P", "~", "\n", "π", "Π"]
      - ["z", "Z", "`", "↶", "ζ", "ℤ"]
      - ["b", "B", "+", ":", "β", "⇐"]
      - ["m", "M", "%", "1", "μ", "⇔"]
      - [",", "–", '"', "2", "ϱ", "⇒"]
      - [".", "•", "'", "3", "ϑ", "↦"]
      - ["j", "J", ";", ".", "θ", "Θ"]
      - [""]
    # Row 4, containing the spacebar and modifiers
    - - ["♕"]
      - [""]
      - ["♔"]
      - ["⇩"]
      - ["⇚"]
      - ["⇧"]
      - ["\n"]
      - [""]
      - [""]
      - [""]
      - [""]
      - ["⌫"]
      - [" ", " ", " ", "0", " ", " "]
      - [""]
      - ["♖"]
      - [""]
      - [""]
      - ["♕"]

  fixed_keys:
    - [  true,  true,  true,  true,  true,  true, true,                           true, true,  true,  true,  true,  true,  true]
    - [  true, false, false, false, false, false, true,                           true, false, false, false, false, false, false]
    - [  true, false, false, false, false, false, true,                           true, false, false, false, false, false, false]
    - [  true, false, false, false, false, false,                                       false, false, false, false, false, true]
    - [  true,  true,  true,  true,  true,  true,  true, true, true,  true, true, true, true,  true,  true,  true,  true,  true]

  # for NeoLayoutGenerator:
  # layers that shall not be permutated (starting from 0)
  fixed_layers: [2, 3]

  # for GroupedLayoutGenerator:
  # number of consecutive symbols from base layout to group together generating a layout
  grouped_layers: 2

  modifiers:
    - Left:
        type: hold
        value: [[6,4]]
      Right:
        type: hold
        value: [[6,4]]
    - Left:
        type: hold
        value: [[4,4]]
      Right:
        type: hold
        value: [[4,4]]
    - Left:
        type: hold
        value: [[5,4]]
      Right:
        type: hold
        value: [[5,4]]
    - Left:
        type: hold
        value: [[15,4]]
      Right:
        type: hold
        value: [[15,4]]
    - Left:
        type: hold
        value: [[4,4], [5,4]]
      Right:
        type: hold
        value: [[4,4], [5,4]]
