keyboard:
  matrix_positions:
    - [[0,0],    [1,0], [2,0], [3,0], [4,0], [5,0], [6,0],   [13,0], [14,0], [15,0], [16,0], [17,0], [18,0], [19,0]]
    - [[0,1],          [2,1], [3,1], [4,1], [5,1], [6,1],   [13,1], [14,1], [15,1], [16,1], [17,1], [18,1], [19,1]]
    - [[0,2],            [2,2], [3,2], [4,2], [5,2], [6,2],   [13,2], [14,2], [15,2], [16,2], [17,2], [18,2], [19,2], [20,2]]
    - [[0,3],    [1,3],    [2,3], [3,3], [4,3], [5,3], [6,3],   [13,3], [14,3], [15,3], [16,3], [17,3], [18,3]]
    - [[0,4], [1,4], [2,4],                             [6,4],                        [16,4], [17,4], [18,4], [19,4]]

  positions:
    - [[ 25.5, 25.5],   [ 75.5, 25.5],   [125.5, 25.5],   [175.5, 25.5],   [225.5, 25.5],   [275.5, 25.5],   [325.5, 25.5],   [375.5, 25.5],   [425.5, 25.5],   [475.5, 25.5],   [525.5, 25.5],   [575.5, 25.5],   [625.5, 25.5],   [701.5, 25.5]]
    - [   [ 38.5, 75.5],   [101.5, 75.5],   [151.5, 75.5],   [201.5, 75.5],   [251.5, 75.5],   [301.5, 75.5],   [351.5, 75.5],   [401.5, 75.5],   [451.5, 75.5],   [501.5, 75.5],   [551.5, 75.5],   [601.5, 75.5],   [651.5, 75.5],   [721, 75.5]]
    - [      [  45,125.5],    [114.5,125.5],   [164.5,125.5],   [214.5,125.5],   [264.5,125.5],   [314.5,125.5],   [364.5,125.5],   [414.5,125.5],   [464.5,125.5],   [514.5,125.5],   [564.5,125.5],   [614.5,125.5],   [664.5,125.5]]
    - [[ 30.5, 175.5],    [ 85.5,175.5],   [135.5,175.5],  [185.5,175.5],   [235.5,175.5],   [285.5,175.5],   [335.5,175.5],   [385.5,175.5],   [435.5,175.5],   [485.5,175.5],   [535.5,175.5],   [585.5,175.5],   [681.5,175.5]]
    - [   [ 38.5,225.5],   [101.5,225.5],      [164.5,225.5],                                                   [351.5,225.5],                                         [538.5,225.5],                [601.5,225.5],   [651.5,225.5],   [714.5,225.5]]

  hands:
    - [Left,    Left, Left, Left, Left, Left, Left,   Right, Right, Right, Right, Right, Right, Right]
    - [Left,       Left, Left, Left, Left, Left,   Right, Right, Right, Right, Right, Right, Right]
    - [Left,         Left, Left, Left, Left, Left,   Right, Right, Right, Right, Right, Right, Right, Right]
    - [Left,    Left,    Left, Left, Left, Left, Left,   Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left,                     Left,                      Right, Right, Right, Right]

  fingers:
    - [Pinky,    Pinky, Pinky, Ring, Middle, Index, Index,   Index, Index, Middle, Ring, Pinky, Pinky, Pinky]
    - [Pinky,       Pinky, Ring, Middle, Index, Index,   Index, Index, Middle, Ring, Pinky, Pinky, Pinky]
    - [Pinky,         Pinky, Ring, Middle, Index, Index,   Index, Index, Middle, Ring, Pinky, Pinky, Pinky, Pinky]
    - [Pinky,   Pinky,   Pinky, Ring, Middle, Index, Index,   Index, Index, Middle, Ring, Pinky, Pinky]
    - [Pinky, Ring, Thumb,                          Thumb,                      Thumb, Middle, Ring, Pinky]

  key_costs:
    - [80,   70, 60, 50, 50, 50, 60,   60, 50, 50, 50, 60, 70, 80]
    - [24,      16, 10,  5, 12, 17,   20, 13,  5,  9, 11, 20, 36]
    - [ 9,         5,  3,  3,  3,  8,    8,  3,  3,  3,  5,  9, 30, 6]
    - [20,   16,    19, 22, 22, 14, 30,   10, 12, 20, 20, 17, 19]
    - [30, 20,  10,             3,              10, 20, 30, 40]

  unbalancing_positions:
    - [[-2, 2],  [-1.5,3],    [0, 3],   [0, 2],   [0, 1],   [0, 2],   [1, 3],       [-1, 3],   [0, 2],   [0, 1],   [0, 2],   [0, 3],   [1.5, 3],   [3, 3]]
    - [[-1, 1],      [0,0.7],    [0, 0],   [0, 0],   [0,0.1],   [1, 1],       [-1.5,1], [-.5,.5], [0, 0],   [0, 0],   [0,0.3],  [1, 1],   [2, 1.5]]
    - [[-1, 0],           [0, 0],   [0, 0],   [0, 0],   [0, 0],    [1, 0],       [-1, 0],  [0, 0],   [0, 0],   [0, 0],   [0, 0],   [1, 0],   [2, 0],  [3, 0]]
    - [[-1,-1],  [0,  0],     [0, 0],  [.5,-.5], [.5,-.5], [0, 0],   [2, -.5],      [0, 0],   [0, 0],   [0, 0],   [0, 0],   [0, 0],   [1, -1]]
    - [[-2,-2],  [0,-2], [0,-1],                                     [0, 0],                        [0,-1],   [0,-2],   [0,-3],   [1,-3]]

  symmetries:
    - [  1,       2,   3,   4,   5,   6,   7,    7,   6,   5,   4,   3,   2,   1]
    - [  9,          10,  11,  12,  13,  14,    14,  13,  12,  11,  10,   9,  15]
    - [ 16,            17,  18,  19,  20,  21,    21,  20,  19,  18,  17,  16,  22,  23]
    - [ 24,      25,     26,  27,  28,  29,  30,     30,  29,  28,  27,  26,  24]
    - [ 31,  32,  33,                      34,                       35,  36,  37,  38]

  finger_resting_positions:
    Left:
      Pinky: [114.5, 125.5]
      Ring: [164.5, 125.5]
      Middle: [214.5, 125.5]
      Index: [264.5, 125.5]
      Thumb: [351.5, 225.5]
    Right:
      Pinky: [564.5, 125.5]
      Ring: [514.5, 125.5]
      Middle: [464.5, 125.5]
      Index: [414.5, 125.5]
      Thumb: [351.5, 225.5]


  plot_template: |2
    ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬──────┐
    │ {{0}} │ {{1}} │ {{2}} │ {{3}} │ {{4}} │ {{5}} │ {{6}} │ {{7}} │ {{8}} │ {{9}} │ {{10}} │ {{11}} │ {{12}} │ {{13}}    │
    ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬────┤
    │   {{14}} │ {{15}} │ {{16}} │ {{17}} │ {{18}} │ {{19}} │ {{20}} │ {{21}} │ {{22}} │ {{23}} │ {{24}} │ {{25}} │ {{26}} │ Ret│
    ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐   │
    │    {{27}} │ {{28}} │ {{29}} │ {{30}} │ {{31}} │ {{32}} │ {{33}} │ {{34}} │ {{35}} │ {{36}} │ {{37}} │ {{38}} │ {{39}} │ {{40}} │
    ├────┬─┴─┬─┴─┬─┴─┬─┴─┯─┴─┬─┴─┬─┴─┯─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴───┤
    │  {{41}} │ {{42}} │ {{43}} │ {{44}} │ {{45}} │ {{46}} │ {{47}} │ {{48}} │ {{49}} │ {{50}} │ {{51}} │ {{52}} │    {{53}}    │
    ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴─┬─┴──┬┴───┼────┬────┤
    │  {{54}} │ {{55}}  │ {{56}}  │           {{57}}           │  {{58}} │  {{59}} │  {{60}} │  {{61}} │
    └────┴────┴────┴───────────────────────┴────┴────┴────┴────┘


  plot_template_short: |2
    {{0}}{{1}}{{2}}{{3}}{{4}} {{5}}{{6}}{{7}}{{8}}{{9}}{{10}}{{11}}
    {{12}}{{13}}{{14}}{{15}}{{16}} {{17}}{{18}}{{19}}{{20}}{{21}}⇘
    {{22}}{{23}}{{24}}{{25}}{{26}} {{27}}{{28}}{{29}}{{30}}{{31}}

base_layout:
  keys:
    # Row 0 (number row)
    - - ["`", "¬"]
      - ["1", "!"]
      - ["2", '"']
      - ["3", "£"]
      - ["4", "$"]
      - ["5", "%"]
      - ["6", "^"]
      - ["7", "&"]
      - ["8", "*"]
      - ["9", "("]
      - ["0", ")"]
      - ["-", "—"]
      - ["=", "+"]
      - ["←"]
    # Row 1
    - - ["⇥"]
      - ["q", "Q"]
      - ["w", "W"]
      - ["e", "E"]
      - ["r", "R"]
      - ["t", "T"]
      - ["y", "Y"]
      - ["u", "U"]
      - ["i", "I"]
      - ["o", "O"]
      - ["p", "P"]
      - ["[", "{"]
      - ["]", "}"]
    # Row 2 (home row)
    - - [""]
      - ["a", "A"]
      - ["s", "S"]
      - ["d", "D"]
      - ["f", "F"]
      - ["g", "G"]
      - ["h", "H"]
      - ["j", "J"]
      - ["k", "K"]
      - ["l", "L"]
      - [";", ":"]
      - ["'", "@"]
      - ["#", "~"]
      - ["\n"]
    # Row 3
    - - ["⇧"]
      - ["\\", "|"]
      - ["z", "Z"]
      - ["x", "X"]
      - ["c", "C"]
      - ["v", "V"]
      - ["b", "B"]
      - ["n", "N"]
      - ["m", "M"]
      - [",", "<"]
      - [".", ">"]
      - ["/", "?"]
      - ["⇗"]
    # Row 4, containing the spacebar
    - - ["♕"]
      - [""]
      - ["♔"]
      - [" "]
      - [""]
      - [""]
      - [""]
      - ["♛"]

  fixed_keys:
    - [ true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true]
    - [ true, false, false, false, false, false, false, false, false, false, false,  true,  true]
    - [ true, false, false, false, false, false, false, false, false, false,  true,  true,  true,  true]
    - [ true,  true, false, false, false, false, false, false, false, false, false,  true,  true]
    - [ true,  true,  true,                       true,                       true,  true,  true,  true]

  # for NeoLayoutGenerator:
  # layers that shall not be permutated (starting from 0)
  fixed_layers: []

  # for GroupedLayoutGenerator:
  # number of consecutive symbols from base layout to group together generating a layout
  grouped_layers: 2

  modifiers:
    - Left:
        type: hold
        value: [[0,3]]
      Right:
        type: hold
        value: [[18,3]]
