[default]
allowed_cors_origins = "http://localhost:8080"
default_layout_config = "standard"
eval_parameters = "../../config/evaluation/default.yml"
layout_configs = [
  [
    "standard",
    "../../config/keyboard/standard.yml",
  ],
  [
    "ortho",
    "../../config/keyboard/ortho.yml",
  ],
  [
    "moonlander",
    "../../config/keyboard/moonlander.yml",
  ],
  [
    "crkbd",
    "../../config/keyboard/crkbd.yml",
  ],
  [
    "lily58",
    "../../config/keyboard/lily58.yml",
  ],
  [
    "ansi",
    "../../config/keyboard/standard_qwerty_ansi.yml",
  ],
]
ngrams = "../../ngrams/deu_mixed_wiki_web_0.6_eng_news_typical_wiki_web_0.4"
secret = "super_duper_secret"
static_dir = "static"

[default.databases.sqlx]
url = "postgres://postgres:super_secret@localhost:15432/postgres"
