metrics:

  oxey_sfbs:
    enabled: true
    weight: 1.0
    normalization:
      type: weight_all
      value: 0.01  # bring to percent
    params:
      exclude_thumbs: false
      exclude_modifiers: false
      exclude_chars: []

  oxey_lsbs:
    enabled: true
    weight: 1.0
    normalization:
      type: weight_all
      value: 0.01
    params:
      exclude_thumbs: true
      exclude_modifiers: false
      exclude_chars: []

  oxey_dsfbs:
    enabled: true
    weight: 1.0
    normalization:
      type: weight_all
      value: 0.01
    params:
      exclude_thumbs: false
      exclude_modifiers: false
      exclude_chars: []

  oxey_inward_rolls:
    enabled: true
    weight: &roll_inwards 1.0
    normalization:
      type: weight_all
      value: 0.01
    params:
      exclude_thumbs: false
      exclude_modifiers: false
      exclude_chars: []

  oxey_outward_rolls:
    enabled: true
    weight: &roll_outwards 1.0
    normalization:
      type: weight_all
      value: 0.01
    params:
      exclude_thumbs: false
      exclude_modifiers: false
      exclude_chars: []

  oxey_onehands:
    enabled: true
    weight: &same_hand_roll 1.0
    normalization:
      type: weight_all
      value: 0.01
    params:
      exclude_thumbs: false
      exclude_modifiers: false
      exclude_chars: []

  oxey_alternates:
    enabled: true
    weight: &alternate_other_finger 1.0
    normalization:
      type: weight_all
      value: 0.01
    params:
      exclude_thumbs: false
      exclude_modifiers: false
      exclude_chars: []

  oxey_alternates_sfs:
    enabled: true
    weight: &alternate_same_finger 1.0
    normalization:
      type: weight_all
      value: 0.01
    params:
      exclude_thumbs: false
      exclude_modifiers: false
      exclude_chars: []

  oxey_redirects:
    enabled: true
    weight: &same_hand_redirect 1.0
    normalization:
      type: weight_all
      value: 0.01
    params:
      exclude_thumbs: false
      exclude_modifiers: false
      exclude_chars: []

  oxey_bad_redirects:
    enabled: true
    weight: &same_hand_bad_redirect 1.0
    normalization:
      type: weight_all
      value: 0.01
    params:
      exclude_thumbs: true  # consider thumb an index finger
      exclude_modifiers: false
      exclude_chars: []

  oxey_combined_trigram:
    enabled: true
    weight: 0.0
    normalization:
      type: weight_all
      value: 0.01
    params:
      exclude_thumbs: false
      exclude_modifiers: false
      exclude_chars: []
      same_hand_double_finger_repeat: 0.0
      same_hand_single_finger_repeat: 0.0
      same_hand_roll: *same_hand_roll
      same_hand_redirect: *same_hand_redirect
      same_hand_bad_redirect: *same_hand_bad_redirect
      roll_same_finger: 0.0
      roll_inwards: *roll_inwards
      roll_outwards: *roll_outwards
      roll_other: 0.0
      alternate_other_finger: *alternate_other_finger
      alternate_same_key: -1.0
      alternate_finger_repeat: *alternate_same_finger

ngrams:
  # Increase the weight of bigrams that have both an absolute weight and relative weight exceed
  # specified thresholds.
  increase_common_ngrams:
    enabled: false
    # Bigrams with a relative weight exceeding this threshold are considered
    critical_fraction: 0.001
    # The weight for bigrams exceeding both thresholds is multiplied by this factor
    factor: 2.0
    # Bigrams with an absolute weight exceeding this threshold are considered
    total_weight_threshold: 20.0


ngram_mapper:
  # Exclude ngrams that contain a line break, followed by a non-line-break character.
  # This encodes a mental pause which usually comes after hitting the "Enter" key, before
  # continuing to write.
  exclude_line_breaks: false

  # Split symbols belonging to higher layers of the layout into combinations involving modifiers
  # required to activate the layer
  split_modifiers:
    enabled: false
    # Multiply the ngram's weight with this factor whenever the resulting ngram involves two
    # modifiers that are required for the same symbol
    same_key_mod_factor: 0.03125



